### ISSUE TITLE
Alex

### ISSUE THREAD

**Issue by jalex141** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#1]
https://github.com/jalex141/Emo_C3PO.git

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Holaaaaa Alejandro 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

En general el readme esta super bien Alejandro, solo un par de detalles que he visto que podrían mejorar tu readme:

- Te faltan algunos links a algunas librerias de la documentación. Además tienes algunas librerías que están repetidas en el listado.

- Lo que para mi es más importante, cuando creamos una API es esencial una documentación. En este caso debería estar en el readme o en otro archivo tipo readme. ¿Qué deberíamos tener en esta documentación?

  - Cuáles son nuestros endpoints de GET  

  - Cuáles son nuestros endpoints de POST

  - Poner algunos ejemplos de enpoints, con una muestra de lo que nos devolvería cada endpoint

Puede que no sea la versión definitiva del readme como nos dijiste en la presentación, en caso de que sea actualizala! 😉

## Estructura del repo
Suuuper buen trabajo en la organización del repo, solo como detalle: 

- En la carpeta de `notebooks` supongo que los *jupyters* tendrán un orden, en caso de que sea así, si los numeras te quedaría perfectoo


Enhorabuena por esta parte del proyecto Alejandro 💪

## Sintaxis de código
Vamos con la parte del código! 

- En el fichero `data_to_sql.py`  tienes este import comentado

    ```python
    from import tools.sql_tools as sql
    # supongo que no te hará falta, pero como detalle el código en este caso no estaría bien. Tendríamos que hacer:

    import tools.sql_tools as sql
    ```
- Vamos con los *docstrings*, genial que los tengas en todas las funciones 💪. Para tenerlos perfectitos, que es lo que deberíamos poner:

    - ¿Qué es lo que hace la función? En una línea
    - ¿Qué parámetros recibe? Con los tipos de los parámetros, es decir, srting, lista, diccionario etc
    - ¿Qué es lo que nos devuelve la función?

        ```python
        # tomando como ejemplo una función tuya
        def insertCharacter(string):
        """
        calls check function and inserts the character if it does not exist
        Args: 
            string (string): the name of the character
        Returns 
            message bla bla bla 
        """
            if check("character", string):
                return "character exists"
            else:
                engine.execute(f"INSERT INTO characters (name) VALUES ('{string}');")
        # Nota: en caso de que no reciba ningún parámetros, podemos poner None debajo de Args
        ```
- En el jupyter the `clean` tienes funciones en el propio jupyter, ya nos dijiste que no era la definitiva, pero si no lo es muevelas 😉!!

- En la función `substitute` que tienes en el jupyter de `clean`

    ```python
    # a parte de que faltan los docstrings, que sentido tiene que pongas dos lineas de código idénticas dentro de la función? 
    # por otro lado, solo como detalle, podrías haber usado el método replace de pandas. 
    def substitute(x):
        x = str(x).replace("'", " ")
        x = str(x).replace("'", " ")

        return x
    ```
- En el jupyter de `upload`, por ponerme tiquismiquis, los *imports* al inicio del jupyter. 
- Tienes varios *endpoints*  tanto GET como POST, pero sin embargo me ha faltado algún endpoint más, como por ejemplo uno de actualizar alguna entrada usando el `UPDATE` de sql. 


## TODOs

Bueno Alejandro, enorme trabajo en este proyecto, solo puedo darte la enhorabuena. Los comentarios son más detalles que otra cosa. A modo de recap de lo que te dije:

- La documentación de la API, suuper importanteee
- Darle una vueltina a los *docstrings* 
- Algún *endpoint* hubiera esta bien, hubiera cerrado mucho tu proyecto. 


Aún con todos bien hecho Alejandrooooo 💪🔥

![image](https://user-images.githubusercontent.com/75084991/134879660-dd8d9eaa-13a8-4798-a8d5-9c517965834f.png)
