### ISSUE TITLE
Rick and Morty API sentiment analysis. Jorge Solana

### ISSUE THREAD

**Issue by Jorge-Solana** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#2]
https://github.com/Jorge-Solana/Rick-and-Morty-sentiment-analysis

**Comment by AnaAGG** [comment]
# Proyecto Flask

Holaaaaa Jorge 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

Buen trabajo en el readme Jorge, esta bastante completo con el link a la documentación de tu API 👏🏽. Te dejo por aquí algunos detalles que me han faltado para que quede perfecto:

- De dónde has sacado los datos para nutrir tu API, de kaggle, de otra API, mediante *scrapeo* 

- La estructura de carpetas de este repo puede ser un poco más compleja por lo que estaría bien que tuvieras un apartado con la estructura de carpetas que nos tienes y que encontraremos en cada una de ellas (en una línea, algo corto)

Por el resto todo perfecto 😉

## Estructura del repo

En general super bien organizado todo Jorge, aquí algunos detalles para que te quede cerradito del todo 😉: 

- En las carpetas `Config` y `src` se te han pasado unos archivos temporales, el `__pycache`. Recuerda, este tipo de ficheros al `.gitignore`. 

- Por otro lado tienes varios archivos por ahí "sueltos": 
  - `API Calls and NLP Visuals.ipynb` lo ideal a la carpeta de Notebooks.
  - `RickAndMortyScripts.csv` create una carpeta de data.
  - `schema_rick_morty.sql` a una carpeta que se llame SQL, por ejemplo.

## Sintaxis de código

- Lo primerito de todo, aunque no esencial, tenemos que intentar no dejar ficheros vacios. Para mi lo ideal es tener un `.py` con las funciones de check separadas del resto. Pero si decides no hacer esto elimina el fichero vacío. 

## nosql_tools.py

- En esta función `character_sentiment` sacas los datos de una llamada a tu propia API, lo cual esta bien. Pero lo ideal hubiera sido que lo hicieras con una query a tu base de datos de SQL usando el método `pd.read_sql_query`. Te dejo por aquí unas lineas de código por si te aportan valor:  

    ```python
    def character_sentiment(name):
        data = pd.read_sql_query(
            """
            SELECT phrase FROM tutabla 
            WHERE name = '{name}';
            """, engine
        ) # esto nos devolverá todas las frases de determinado personaje

        lista = []
        for i,row in data.iterrows():
            blob = TextBlob(f"{row['phrase']}")
            polarity = blob.sentiment[0]
            lista.append(polarity)
        return sum(lista)/len(lista)
    ```
- Para los diccionarios que te has creado con los ids de los personajes y los episodios. Lo ideal sería que te crearas un nuevo archivo `.py` donde los almacenaremos, lo que haremos será acceder a estos diccionarios de la misma forma que con las funciones en un `.py`. 

    No sé si me estoy explicando muy bien, pero si te quedan dudas sobre esto dime y lo vemos juntos. 

    Con esto nos ahorramos tener que estar metiendo los diccionarios en cada fichero que necesitemos. 

Pero vamos que sobre este fichero tengo que darte la enhorabuena por crearte un ejecutable 👏🏽!!!

## sql_tools.py

Perfectito todo, bien hecho Jorge

## main

- En las funciones del `.py` no hace falta que pongamos los *docstrings*, más por convenio 😉. 

    Por el resto todo perfecto en este fichero Jorge! 

## TODOs

Bueno Jorge, principalmente  te di detalles de tu proyecto, esta suuper bien 💪. A modo de resumen:

- Crearte alguna carpeta más en tu repo para no tener archivos por ahí sueltos
- ¿De dónde salen los datos?
- Crear el `.py` con los diccionarios


Suuper bien trabajado Jorge, a pesar de la frustación y todos los problemitas sacaste un proyecto excelente! 

![image](https://user-images.githubusercontent.com/75084991/134535769-b0433384-3994-4404-b97b-31d97803c709.png)
