### ISSUE TITLE
GetVidya https://github.com/DiegoCefalo/GetVidya

### ISSUE THREAD

**Issue by DiegoCefalo** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#3]
https://github.com/DiegoCefalo/GetVidya

**Comment by AnaAGG** [comment]
# Proyecto Flask 
Holaaaaa Diego 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

El readme esta perfecto Diego, buen trabajo. Solo algún detalle: 

- Podrías haber puesto algún ejemplo de llamada a tu API, es decir, que nos devuelven algunos de tus *endpoints*

- Este proyecto ya tiene una estructura de carpetas algo más compleja por lo que te recomendaría que pusieras un nuevo apartado con la estructura de carpetas que tienes en tu repo, explicando en una línea lo que nos podemos encontrar en cada una de ellas. 
  
Por el resto todo perfectito 👏🏽

## Estructura del repo

Peeerfecta Diegoooo 🚀

Solo como detalle, para no tener por ahí suelto el jupyter, create una carpeta nueva y mételo ahí 😉

## Sintaxis de código

Vamos con la parte de código

- **SQL**  

    Todo bien en esta carpeta Diego, pequeños ficheros con queries específicas! 
- **tools**

    Los endpoints que tienes creados están perfectos. Peeero me han faltado algunos endpoints de POST. 

    Entiendo que el de `delete` puedas creer que no tiene mucho sentido, pero puede que algún usuario meta algún comentario equivocado que haga falta quitar. 

    Pero el que sin duda tendrías que haber hecho es el de `update` 😔

    🚨 Me falta el endpoint del análisis de sentimientos!

- **demo** 
  - Recuerda, los `import` siempre al inicio del jupyter. 

- **Análisis de sentimientos**

    🔴 Diego... no veo tu código del análisis de sentimientos por ningún lado de la misma forma que solo tienes una figura del análisis de sentimientos. 

    Con todos los datos que tienes podrías haber sacado muchas más gráficas aportando mucho más valor a tu proyecto


## TODOs

- El código del análisis de sentimientos lo más importante Diego!
- Incluir algún endpoint más de POST. 
- Ejemplos de los endpoints de tu API. 

Bueno Diego, proyecto suuperado. Con todo, en este proyecto hemos aprendido como crear una API usando Flask, hemos usando SQL y le hemos perdido el miedo 💪.

![image](https://user-images.githubusercontent.com/75084991/134337781-f1d2ca6e-936e-4b3b-88e4-c9db81c46ade.png)
