### ISSUE TITLE
The X Files Sentiment

### ISSUE THREAD

**Issue by JulianTrufero** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#4]

**Comment by AnaAGG** [comment]
# Proyecto Flask

Holaaaaa Julián 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

¿Qué ha pasado con el readme Julián 😔?

Supongo que no te dio tiempo a escribirlo, pero te animo a que lo hagas. 

Como puntos importantes en este readme son: 

- Poner algún ejemplo de lo que nos devolverían algunos de los *endpoints*  de tu API
- Como este repo tiene una estructura de carpetas algo más compleja una buena opción es poner un apartado donde expliques la estructura del repo describiendo brevemente lo que nos vamos a encontrar en cada carpeta.  
- De donde has sacado la información para nutrir tu API. 

Creo que a grandes rasgos estos serían los puntos importantes de este readme 😉

## Estructura del repo

Esta perfecta Julián, buen trabajooooo 💪👏🏽!!! Solo un detallito: 

- En la carpeta de `Notebooks` tienes dos ficheros, no sé si tendrán orden, pero en caso de que lo tengan, si los numeras para saber cual es el orden estaría perfectoooo

Por el resto perfectitoooo, no se te pasó ningún archivo temporal fuera del `.gitignore` y tienes todos tus ficheros super modularizados en carpetas 🚀

## Sintaxis de código

Vamos con la parte de código

- **x_files_db**
  - Tienes algunas funciones en este jupyter, recuerda llevartelas a la carpera `src`. En esta carpeta podemos tener tantos `.py` como queramos, en que cada uno de ellos está destinado a una cosa específica. Por lo tanto, te podrías hacer una `.py` que tuviera esas funciones. 


- **sql_tools**
  - Por ponerme quisquillosa, en los *docstrings* cuando le pasas los `args` lo ideal también sería que indicaras de que tipo son, es decir, si son *str*, *lst*, *int*, *float* etc. 

    Por el resto trabajo impecable Julián 👏🏽! 

## TODOs

- Tienes un documento con la info de la API pero falta lo que viene siendo el readme del proyecto.
- Pasar algunas funciones que tienes el jupyter  a un `.py`
- Revisar un poco los *docstrings* para que te quede perfecto. 


Bueno Julián, los proyectos cada vez van teniendo menos correcciones. Has hecho un trabajo muy bueno en este proyecto, enhorabuena! 

![image](https://user-images.githubusercontent.com/75084991/134469954-4a720d07-0e44-48ad-b8ea-ec1b409fdf51.png)
