### ISSUE TITLE
[Oasis song analysis ] Luke Smith

### ISSUE THREAD

**Issue by lukesmith194** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#5]
https://github.com/lukesmith194/oasis_api_project0

**Comment by AnaAGG** [comment]
# Proyecto Flask

Holaaaaa Luke 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

El readme en general esta perfecto, has incluido todos los endpoints que tienes en tu API, tanto los de POST como los de GET. Algunos detalles que podríamos incluir en el readme:

- Podrías incluir algún ejemplo de un *endpoint*,es decir, poner lo que nos devuelve algunos de nuestros *endpoints* 

- Cuando pones los links a la documentación oficial de las librerías parece que no se te renderizó del todo bien. ¿Qué es lo que esta fallando? 

    ```
    Esto es lo que tienes tu: 
    Pandas [here] (https://pandas.pydata.org/docs/)

    ¿Como lo deberíamos poner?
    [Pandas](https://pandas.pydata.org/docs/) # sin espacios entre el corchete y el paréntesis. Lo que veremos con esto es en azulito Pandas donde picharemos y nos llevará a la página. 
    ```
- Como es un repo con una estructura de carpetas algo más compleja, puedes crear un apartado donde expliques la estructura de las carpetas y lo que nos podemos encontrar en ellas. 

Por el resto perfecto Luke, buen trabajoooo

## Estructura del repo

Muy buen trabajo con la estructura del repo Luke, lo tienes todo muy bien organizado 👏🏽. Por ponerme un poco tiquismiquis, te dejo por aquí algunos detalles: 

- Tienes la carpeta de los *checkpoints* del jupyter, recuerda meterla en el `.gitignore`
- Dentro de las carpetas `tools` y `config` también tienes un fichero que se llama `__pyacache__` que deberían ir al `.gitignore`. 
- Si ya metes el jupyter en una carpeta te queda 🔝🔝 la organización del repo.
  
## Sintaxis de código

Vamos con el código: 

- **sqltools**
  - Por ponerme fina fina, tienes los *docstrings* lo cual está perfecto. Peeero cuando pones los args, lo ideal sería que pusieras también el tipo de los parámetros que recibe la función, es decir, si son *string*, *list*, *int* etc. 
  
    Por el resto todo super bien Luke!!

- **NPLtools**
    - Falta el *docstring* de la función *connecttablesart* 

    - Para un futuro, para añadir más valor te podrías crear más endpoints de post, como eliminar (por si alguien mete algo que no está bien, Paco de Lucía por ejemplo) o actualizar por si hubiera algún error. 

    Te dejo por aquí algunas lineas de código con un ejemplo de como podrías eliminar una canción de una de tus tablas. En realidad tu código sería muy similar. 

    ```python

    def deletelyrics(lyrics):

        id_lyrics = check_lyrics(lyrics) # esto se mantedría igual
        if id_lyrics > 0:
            return id_lyrics
        else:
            cursor = engine.execute(f" DELETE FROM  lyrics WHERE idlyrics = id_lyrics;")
            return "la canción fue eliminada correctamente"

    ```
    Por el resto hiciste muy buen trabajo Luke! 


🔴 Como general para todos los archivos, te has creado un par de diccionaros de los que bebes para poder las queries en SQL. Lo que sería ideal ideal es que te crearas un nuevo archivo `.py` que lo llamemos por ejemplo `support` o algo así donde almancenes todos esos diccionarios. Lo que harás después es llamarlos desde cada `.py` que uses como hacemos como cualquier otro `.py`. 

    Tal vez no me este explicando especialmente bien, pero si tienes alguna duda dime y lo vemos juntos. 

    Con esto nos ahorramos tener que estar metiendo los diccionarios en cada fichero que necesitemos. 

- **main** 
    - Nada que decirte en esta parte, lo tienes todo muy modularizado y muy clarito!!! 
En general suuper buen trabajo Luke, has creado tu primera API 🚀!!

## TODOs

Como siempre te dejo por aquí un pequeño recap de la corrección:

- Las librerías en el readme
- Meter algún ejemplo de *endpoint* en el readme
- Quitar los archivos temporales de repo
- Crear algún método de post en la API
- Crear un fichero de `support` donde almacenemos todos los diccionarios que usaremos a lo largo del repo
- Me ha faltado algo de visualización con los datos del análisis de sentimientos. 


Bueno Luke, proyecto suuperado a pesar de los momentos de crisis. Con todo, en este proyecto hemos aprendido como crear una API usando Flask, hemos usando SQL y le hemos perdido el miedo 💪. 

![image](https://user-images.githubusercontent.com/75084991/134311955-c0e238ae-a8ed-411f-947a-9cc72a356ecb.png)
