### ISSUE TITLE
[political_debates_sentiment_analysis] Maria Luisa

### ISSUE THREAD

**Issue by maria-luisa-gomez** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#6]
https://github.com/maria-luisa-gomez/political_debates_sentiment_analysis

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Holaaaaa Maria Luisa 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

Super buen trabajo con el readme! Lo tienes todo muy bien explicado 💪. Un par de detallitos para que quede redondito: 

- Ya que tu datos de vienen de kaggle, estaría genial que pusieras el link a la página de kaggle para que se pueda acceder a ellos y a su información. 

- Este proyecto ya tiene una estructura de carpetas algo más compleja, lo que estaría super bien es que añadieras un poco más de descripción sobre esto. ¿Qué carpetas tenemos? ¿Qué encontraremos en cada carpeta? Luego ya tienes tu explicado lo que hay en cada fichero 👏🏽

- En la documentación de la API también pueden incluir algún ejemplo de lo que nos devuelven algunos *endpoints*, quiero decir, mostrar el `json` que nos devuelve y que información nos da. 


## Estructura del repo

Wow, suuper bien estructurado y organizado 🔝. Te dejo por aquí un par de comentarios: 

- Super bien numerando los jupyters Maria Luisa 👏🏽!

- Esto es más un detallín, pero en la carpeta `src` tienes un archivo de `sql`, lo ideal sería que lo sacaras de ahí ya que esta carpeta esta destinada principalmente a los `.py`. Lo que puedes hacer es crearte una carpeta nueva para el código de SQL. 

Por el resto todo super bien Maria Luisa, no se te ha escapado ningún archivo temporal fuera del `.gitignore` y lo tienes todo muy bien modularizado. Buen trabajo!  

## Sintaxis de código

Poco tengo que decirte aquí Maria Luisa, en general tienes el código super bien 💪👏🏽

- Por ponerme tiquismiquis con los *docstrings*, cuando le pasas los *args* lo ideal es que pusieras de que tipo son los argumentos, es decir, si son `str`, `lst`, `dic` etc. 

- En relación a esta función `all_sentences`: 

    ```python
    def all_sentences():
    """
    Gets all data from political_debates mysql database
   Args:
   query from flask end point http://127.0.0.1:5000/sentences/
   Returns:
       json with query results
    """
        query = f"""
                SELECT * FROM speeches
                INNER JOIN speakers ON speeches.speakers_speakerid = speakers.speakerid
                """

        datos = pd.read_sql_query(query,engine)

        return datos.to_json(orient="records")

    # en los args tienes puesto que la función recibe un parámetro, pero en realidad la función no recibe ninguno (entre paréntesis no tienes nada). En este caso en el docstring en los args tendríamos que poner None
    ```
- Algo similar en esta `speaker_sentence`: 
 

    ```python
    def speaker_sentence(speaker):
    """
    Gets all data from political_debates filtered by given speaker name
    Args:
    query from flask end point http://127.0.0.1:5000/sentences/<speaker>
   Returns:
       json with query results
    """
        query = f"""
                SELECT * FROM speeches
                INNER JOIN speakers ON speeches.speakers_speakerid = speakers.speakerid
                WHERE speaker = '{speaker}'"""

        datos = pd.read_sql_query(query,engine)

        return datos.to_json(orient="records")

    # Pones que los args es la query, pero en realidad el args será un string con el nombre del político del que quieres las frases. 
    ```
- 🔴 Mi recomendación que revises todos los args de tus funciones. 
- En el jupyter *1 - Kaggle data download, cleaning and Mysql upload* al final del todo tienes un par de *for loop* para insertar los datos en SQL, lo ideal es que fueran en un par de funciones. 


## TODOs

Bueno Maria Luisa enhorabuena, te has creado tu propia API, enhorabuena!! Sin embargo hay algunas cosillas que me han faltado, te dejo por aquí algunos comentarios:

- Como detalle, me ha faltado algún endpoint de POST como por el ejemplo un `update` por que una frase este mal o el de `delete`. 

- En la parte del análisis de sentimientos me han faltado algunas gráficas o algo que represente nuestros resultados, al final somos analistas de datos y la visualización 

- Darle una vueltita a los *docstrings* 

- Dejar en el `src` solo archivos `.py`


En conjunto, super buen trabajo Maria Luisa!!!!!


![image](https://user-images.githubusercontent.com/75084991/134670155-e09df9b9-05ee-47d0-bd94-1414244eb239.png)
