### ISSUE TITLE
Top American movies quotes (sentiment analisys)  [Diego Díaz]

### ISSUE THREAD

**Issue by diegodiazgarciadev** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#7]
https://github.com/diegodiazgarciadev/Sentimental-analysis

**Comment by AnaAGG** [comment]
# Proyecto Flask 

Holaaaaa Diego 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

En general el repo esta muy bien Diego, buen trabajo

- Venga, tienes un link con wikipedia para ver de donde sacaste los datos, pero parece que no se te ha renderizado bien 😔. 

    ¿Cómo podemos hacer que se nos vea bien?

    ```
    [wikipedia](https://en.wikipedia.org/wiki/AFI%27s_100_Years...100_Movie_Quotes) # sin espacios entre el corchete y el paréntesis

    # veriamos algo como esto 👇🏽
    ```
    [wikipedia](https://en.wikipedia.org/wiki/AFI%27s_100_Years...100_Movie_Quotes) 

    Lo que esta entre corchetes será lo que se ve en el texto, que si pinchamos nos lleva al link que hay entre paréntesis

- En la parte de las librerias recuerda poner los links a la documentación oficial
- Otra cosita que me ha faltado son algunos ejemplos de los *endpoints*. Quiero decir, tienes explicados todos tus *endpoints* y lo que nos devolvería cada uno de ellos, pero sería ideal si añades un ejemplo con lo que nos devuelve algunos de los *endpoints* de `GET` 

Bueno todo esto son detallitos, como te dije antes, buen trabajo 💪

## Estructura del repositorio

Estupendo el trabajo que has hecho con la organización de tu repo 👏🏽! Solo un detalle: 

- En la carpeta `src` tienes un fichero que se llama `test.py` que esta vacío. Lo ideal sería que lo eliminaras o que lo metieras en el `.gitignore`. 

## Sintaxis de código

- Como detalle en general, cuando haces los *docstrings* y pasas los parámetros que recibe tu función yo le añadiría de que tipo son estos parámetros, es decir, `str`, `lst`, `dic` etc. 

- En esta función `quotesbysexsa` donde devuelves todas las frases por sexo con su análisis de sentimientos tienes tres opciones M, F o B. Peeero... la opción B en realidad sería igual que la función `getallquotessa` donde devuelves todas las frases con su análisis de sentimientos no? O puede que me este perdiendo algo del código 🤔

- Por ponerme fina fina, en esta función `replace_df`

    ```python
    def replace_df(df):
        df.quote = df.quote.str.replace("'", "´")
        df.quote = df.quote.str.replace('"', '')

        df.artist = df.artist.str.replace("'", "´")
        df.character = df.character.str.replace("'", "´")
        df.movie = df.movie.str.replace("'", "´")
        return df
    # Si te fijas, repites la misma línea de código varias veces, ahora es asumible porque tienes pocas columnas, pero que pasaría si tienes muchas? Lo ideal sería, pasarle como parámetro una lista con las columnas que queremos cambiar, o hacer una lista dentro de la función. 

      def replace_df2(df):

        col = ["quote", "artist", "chracter", "movie"]
        for i in col: 
            if i == "quote":
                df[i] = df[i].str.replace("'", "´")
                df[i] = df[i].str.replace('"', '')
            else:
                df[i] = df[i].str.replace("'", "´")
       
        return df
    ```
- Detalle de tiquisimiquis, los *imports* todos al inicio del jupyter 😉
- En el `main.py` no hace falta que le pongamos *docstrings* a las funciones, esto es más convención que otra cosa. 

Por el resto esta todo perfecto Diego, super bien el código en este proyecto 😉!!

## TODOs

- Atomizar esa funcioncita (`replace_df`)
- Terminar de rematar los *docstrings*  y los links de la documentación y la página de wikipedia


Bueno Diego, suuper buen trabajo. Con todo, en este proyecto hemos aprendido como crear una API usando Flask, hemos usando SQL y le hemos perdido el miedo 💪.

![image](https://user-images.githubusercontent.com/75084991/134490369-9f0407fd-578e-4db5-af66-3e48bed28846.png)
