### ISSUE TITLE
Frases, históricas 

### ISSUE THREAD

**Issue by jaimecabanyes** [Ironhack-Data-Madrid-Agosto-2021/W6-api-sentiment-project#9]

**Comment by AnaAGG** [comment]
# Proyecto Flask

Holaaaaa Jaime 🙋🏻‍♀️! Vamos con algunos comentarios del proyecto de Flask 💪

## README

¿Qué ha pasado con el readme Jaime? 😔 Recuerda que es esencial para presentar el proyecto! Se que ahora no estarás pensando mucho en esto, pero te animo a que lo hagas cuando tengas un hueco

## Estructura del repo

En general bien, pero ya sabes que siempre tengo algún detallin que comentar 🤣. Vamos con ellos: 

- Tienes varios jupyters, lo ideal es que los metieras todos en una carpeta que se llame por ejemplo `notebooks` donde los metas. Si además los númeras para saber el orden de trabajo quedaría perfecto 😉! 
- Lo mismo para el `csv` que tienes, puedes meterlo en una carpeta que se llame `data` para que te quede todo mucho más modularizado. 
- En la carpeta `src` tienes un fichero que se llama funciones 😭😫!!! Recuerda evitamos nombres tan generales! 

## Sintaxis de código

Vamos con la parte de código!!

- **Insert data into MySQl done**
  - Tienes por ahí funciones, recuerda llevartelas a un `.py` y ponerles los *docstrings*!!
  - En esta función
    ```python
    # si te fijas en esta función tienes, lo ideal es que lo hicieras con un for loop para evitar repetir la misma línea de código todo el rato. 
    def quitar_tildes(df):
        try:
            df = df.replace("á", "a")
            df = df.replace("é", "e")
            df = df.replace("í", "i")
            df = df.replace("ó", "o")
            df = df.replace("ú", "u")
        except:
            pass
        return df
    ```
  - Te dejaste la contraseña de muysql en el jupyter, recuerda llevartela al `.env`

-  **SQL_Alchemy_conexion**
  
   -  Lo mismo que en el otro jupyter, las funciones al `.py`

   -  Por el resto todo bien, solo eso, incluir las funciones en `.py` para que nuestro jupyter esta más limpito 😃

- **funciones.py** 

  - Los nombres de las funciones en minúscula!! Esto es convenio de python, funciones en minúscula y clases en mayúscula! 

  - Vamos con los *docstrings* , genial que los tengas en las funciones 🔝. Para tenerlos perfectitos, que es lo que deberíamos poner:

    - ¿Qué es lo que hace la función? En una línea
    - ¿Qué parámetros recibe? Con los tipos de los parámetros, es decir, srting, lista, diccionario etc
    - ¿Qué es lo que nos devuelve la función?

    ```python
    # vamos a ver un ejemplo con una función tuya


    def df_sentimientos(name):
        """
        This function joins the 2 previous datfarmes
        Args: 
            name(string): the name of the character
        Returns:
            A json where we can see the sentiment each author has said.
        """
        j = sql_dataframe(f'{name}')
        k = sentimientos(j)
        k['Frase']= j 
        return k.to_json()
    ```
  - Esto `sia = SentimentIntensityAnalyzer()` lo tienes fuera de una funcón, lo ideal es que lo metieras dentro de la función correspondiente

Por el resto todo perfecto Jaime, enhorabuena, muy buen trabajoooo 💪

## TODOs
Como siempre te hago un recap con los puntos más importantes de tu proyecto: 

- El readme, suuper importantee
- Los *docstrings* de las funciones
- Atomizar un poco más el código


Aún con todos bien hecho Jaime 💪🔥

![image](https://user-images.githubusercontent.com/75084991/134895528-495d814b-afad-4e27-8e1a-29ad9c7c6396.png)
